### ISSUE TITLE
S1 SLC data preprocessing

### ISSUE THREAD

**Issue by juansensio** [jie666-6/UrbanSARFloods#2]
Hello, following your paper

3.1. Preprocessing
The Sentinel-1 Level-1 Interferometric Wide Swath SLC
data, downloaded from Alaska Satellite Facility (ASF),
were used to extract interferograms and then calibrated
and transformed into intensity (in dB). The multilooking (4
looks in the range and 1 looks in the azimuth) was carried
out in order to get the interferogram with the square pixels.
A Goldstein filter with a size of 9 × 9 pixels was applied to
the interferogram to reduce noise in the phase, and then the
interferometric coherence was estimated by a moving window of 9 × 9 pixels. All the intensity and coherence data
were geocoded to World Geodetic System (WGS) 1984 longitude and latitude with 20 m spatial resolution.

Would it be possible to share the code to perform this preprocessing ? I want to train a model with your dataset but I am afraid I will not be able to use it for inference on new data without the same preprocessing.

Thanks

**Comment by jie666-6** [comment]
The preprocessing was carried out by software. You can use SNAP, SARScape or GAMMA, following the described preprocess steps.

**Comment by juansensio** [comment]
Thanks, curious to know why you choose this particular preprocessing that makes it so difficult to actually use a model trained on the data. Why not use other S1 processing levels "ready to use" ?

**Comment by jie666-6** [comment]
Because there is no ready-to-use S1 intensity and coherence data in 20m resolution

**Comment by juansensio** [comment]
I understand. Thanks for the response.
